# control_node:
#   ros__parameters:
    
control_node:
  ros__parameters:
    lookahead_distance: 0.5  # Meters
    goal_tolerance: 0.1      # Meters
    linear_speed: 0.3        # Meters per second
    max_angular_speed: 0.5   # Radians per second
